DATABASE = 'scores.db'
DEBUG = True

SECRET_KEY = 'itsaSECRET' # YOU SHOULD CHANGE THIS

J_USERNAME = 'jele'
J_PASSWORD = 'passwort'
T_USERNAME = 'timo'
T_PASSWORD = 'passwort'

TRAP_BAD_REQUEST_ERRORS = True