DATABASE = 'scores.db'
DEBUG = True

SECRET_KEY = 'itsaSECRET' # YOU SHOULD CHANGE THIS

USERNAME_1 = 'jele'
PASSWORD_1 = 'passwort'
USERNAME_2 = 'timo'
PASSWORD_2 = 'passwort'

TRAP_BAD_REQUEST_ERRORS = True